=== grzes9525/JMS/src/main/resources/schema/INCResponses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- VERSION 3.0.0 -->
<xs:schema targetNamespace="INC" xmlns="INC" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:include schemaLocation="INCErrorResponse.xsd" />

	<xs:include schemaLocation="prepaid/INCPrePaidResponses.xsd" />
	<xs:include schemaLocation="vpabx/legacy/INCVpabxLegacyResponses.xsd" />
	<xs:include schemaLocation="vpabx/conf/INCVpabxConfResponses.xsd" />
	<xs:include schemaLocation="business/suite/INCPostPaidResponses.xsd" />
	
	<xs:include schemaLocation="special/INCConditionalOutpaymentResponse.xsd" />
	<xs:include schemaLocation="special/INCSogSubscriptionExpirationResponse.xsd" />
	<xs:include schemaLocation="special/INCSogSubscriptionsRepairResponse.xsd" />

	<xs:complexType name="t_responseHeader">
		<xs:annotation>
			<xs:documentation>Element common for all response types.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="msgSeqID" type="xs:string" />
			<xs:element name="HLTID" type="xs:string" minOccurs="0" />
			<xs:element name="GID" type="t_GID" minOccurs="0" />
			<!-- identifier of a batch operation that this request belongs to -->
			<xs:element name="batchID" type="xs:string" minOccurs="0" />
			<xs:element name="additionalInfo" type="t_attribute" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:group name="t_specialResponsesBodies">
		<xs:choice>
		
			<!-- internal -->
			<xs:element name="conditionalOutpaymentResponse" type="t_conditionalOutpaymentResponse" />
			<xs:element name="sogSubscriptionExpirationResponse" type="t_sogSubscriptionExpirationResponse" />
			<xs:element name="sogSubscriptionsRepairResponse" type="t_sogSubscriptionsRepairResponse" />

			<!-- batch -->
			<xs:element name="batchResponse" type="t_batchResponse" />
			
		</xs:choice>
	</xs:group>	
	
	<xs:complexType name="t_responseBody">
		<xs:choice>
			<xs:element name="errorResponse" type="t_errorResponse" />
			<xs:group ref="t_prePaidResponsesBodies"/>
<!--			<xs:group ref="t_specialResponsesBodies"/>
			<xs:group ref="t_postPaidResponsesBodies"/>  
			<xs:group ref="t_vpabxLegacyResponsesBodies"/>
			<xs:group ref="t_vpabxConfResponsesBodys"/>-->
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="t_batchResponse">
		<xs:sequence>
			<xs:element name="step" type="t_responseBody" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="t_AInterfaceResponse">
		<xs:annotation>
			<xs:documentation>Top level element for A-Interface responses.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="header" type="t_responseHeader" />
			<xs:element name="body" type="t_responseBody" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="AInterfaceResponse" type="t_AInterfaceResponse" />

</xs:schema>

=== grzes9525/JMS/src/main/resources/xml/AInterfaceResponse3.xml
<?xml version="1.0" encoding="UTF-8"?>
<AInterfaceResponse xmlns="INC"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="INC file:/C:/workspace/JMS/src/main/resources/schema/INCResponses.xsd">
    <header>
        <msgSeqID>msgSeqID0</msgSeqID>
        <HLTID>HLTID0</HLTID>
        <GID>GID0</GID>
        <batchID>batchID0</batchID>
        <additionalInfo name="name1">additionalInfo0</additionalInfo>
        <additionalInfo name="name3">additionalInfo1</additionalInfo>
    </header>
    <body>
<!--        <errorResponse>
            <RC>5000</RC>
            <description>description0</description>
            <requestType>requestType0</requestType>
            <details>details0</details>
        </errorResponse>-->
<!--        <getDynamicDataResponse>
            <MACAccount>
                <expiryDate>2006-05-04</expiryDate>
                <balance>0</balance>
                <grossBalance>0</grossBalance>
            </MACAccount>
            <subaccount>
                <subaccountName>subaccountName0</subaccountName>
                <activationDate>2006-05-04</activationDate>
                <activationTime>01:01:01.001</activationTime>
                <expiryDate>2006-05-04</expiryDate>
                <expiryTime>01:01:01.001</expiryTime>
                <balance>0</balance>
                <grossBalance>0</grossBalance>
                <multibucket>false</multibucket>
                <unit_pack>
                    <validityPeriod>50</validityPeriod>
                    <currentBalance>50</currentBalance>
                </unit_pack>
                <unit_pack>
                    <toDate>2006-05-04T18:13:51.0</toDate>
                    <fromDate>2006-05-04T18:13:51.0</fromDate>
                    <currentBalance>50</currentBalance>
                </unit_pack>
            </subaccount>
            <subaccount>
                <subaccountName>subaccountName1</subaccountName>
                <activationDate>2006-05-04</activationDate>
                <activationTime>01:01:01.001</activationTime>
                <expiryDate>2006-05-04</expiryDate>
                <expiryTime>01:01:01.001</expiryTime>
                <balance>0</balance>
                <grossBalance>0</grossBalance>
                <multibucket>false</multibucket>
                <unit_pack>
                    <validityPeriod>50</validityPeriod>
                    <currentBalance>50</currentBalance>
                </unit_pack>
                <unit_pack>
                    <validityPeriod>50</validityPeriod>
                    <currentBalance>50</currentBalance>
                </unit_pack>
            </subaccount>
            <counter>
                <counterName>counterName0</counterName>
                <currentValue>-1073741773</currentValue>
                <datePeriod>2006-05-04</datePeriod>
            </counter>
            <counter>
                <counterName>counterName1</counterName>
                <currentValue>-1073741773</currentValue>
                <datePeriod>2006-05-04</datePeriod>
            </counter>
        </getDynamicDataResponse>
-->
<!--        <batchResponse>
            <step>
                <updateMUGServiceResponse/>
            </step>
            <step>
                <createSubscriberResponse>
                    <inID>inID0</inID>
                </createSubscriberResponse>
            </step>
        </batchResponse>
-->
<!--        <removeCalendarResponse/>
-->
<!--        <updateVPABXGroupHGResponse/>
-->
<!--        <initAddMemberResponse/>-->
<!--        <initRemoveMemberResponse/>-->
<!--        <activateMemberRoamingCutOffResponse/>-->
<!--        <deactivateMemberRoamingCutOffResponse/>-->
<!--        <activateMemberSecretaryCallResponse/>-->
<!--        <deactivateMemberSecretaryCallResponse/>-->
<!--        <setMemberAclipResponse/>-->
<!--        <addFaxResponse/>-->
<!--        <removeFaxResponse/>-->
<!--        <setFaxAutodetectionResponse/>-->
<!--        <importMemberResponse/>-->
<!--        <getClientContractsResponse>
            <subscriber>
                <number>000000000</number>
                <shortNumber>shortNumber0</shortNumber>
                <type>INTERNAL</type>
                <status>FREE</status>
                <vpnFeature>false</vpnFeature>
                <vpnFmsNumber>000000000</vpnFmsNumber>
                <vpnFmsShortNumber>vpnFmsShortNumber0</vpnFmsShortNumber>
            </subscriber>
            <subscriber>
                <number>000000000</number>
                <shortNumber>shortNumber1</shortNumber>
                <type>INTERNAL</type>
                <status>FREE</status>
                <vpnFeature>false</vpnFeature>
                <vpnFmsNumber>000000000</vpnFmsNumber>
                <vpnFmsShortNumber>vpnFmsShortNumber1</vpnFmsShortNumber>
            </subscriber>
        </getClientContractsResponse>-->
<!--        <setAlertingAnnouncementResponse/>-->
<!--        <setWelcomeAnnouncementResponse/>-->
<!--        <activateScenarioResponse/>-->
<!--        <setCalendarResponse/>-->
<!--        <setFailedCallTreatmentResponse/>-->
<!--        <setVoiceMailBoxNumberResponse/>-->
<!--        <querySubscribersResponse>
            <subscriber>
                <number>000000000</number>
                <shortNumber>shortNumber2</shortNumber>
                <type>INTERNAL</type>
                <status>FREE</status>
                <vpnFeature>false</vpnFeature>
                <vpnFmsNumber>000000000</vpnFmsNumber>
                <vpnFmsShortNumber>vpnFmsShortNumber2</vpnFmsShortNumber>
            </subscriber>
            <subscriber>
                <number>000000000</number>
                <shortNumber>shortNumber3</shortNumber>
                <type>INTERNAL</type>
                <status>FREE</status>
                <vpnFeature>false</vpnFeature>
                <vpnFmsNumber>000000000</vpnFmsNumber>
                <vpnFmsShortNumber>vpnFmsShortNumber3</vpnFmsShortNumber>
            </subscriber>
        </querySubscribersResponse>-->
<!--        <getUnansweredCallsListResponse>
            <unansweredCall>
                <number>000000000</number>
                <timeConnected>2006-05-04T18:13:51.0</timeConnected>
                <duration>0</duration>
            </unansweredCall>
            <unansweredCall>
                <number>000000000</number>
                <timeConnected>2006-05-04T18:13:51.0</timeConnected>
                <duration>0</duration>
            </unansweredCall>
        </getUnansweredCallsListResponse>-->
<!--        <activateVpabxRoamingCutOffResponse/>-->
<!--        <deactivateVpabxRoamingCutOffResponse/>-->
<!--        <removeMsisdnFromAllVpabxsResponse/>-->
<!--        <sendEmailResponse/>-->
<!--        <addVpnFmsNumberResponse/>-->
<!--        <addMemberResponse/>-->
<!--        <removeMemberResponse/>-->
<!--        <activateVpabxServiceResponse/>-->
<!--        <deactivateVpabxServiceResponse/>-->
<!--        <enableVpabxServiceResponse/>-->
<!--        <disableVpabxServiceResponse/>-->
<!--        <modifyVpabxServiceResponse/>-->
<!--        <changeMemberNumberResponse/>-->
        <changeVpabxCCNNumberResponse/>
<!--        <modifyMemberResponse/>-->
<!--        <removeVpnFmsNumberResponse/>-->
<!--        <activateVpabxAclipResponse/>-->
<!--        <deactivateVpabxAclipResponse/>-->
<!--        <activateVpabxSecretaryCallResponse/>-->
<!--        <deactivateVpabxSecretaryCallResponse/>-->
<!--        <removeMemberFromAllVpabxsResponse/>-->
<!--        <removeVpabxOnlyFromDatabaseResponse/>-->
    </body>
</AInterfaceResponse>
